### ISSUE TITLE
U老师您数学库矩阵运算有点Bug

### ISSUE THREAD

**Issue by fakersaber** [Ubpa/RenderLab#3]
在Mat4x4.h的 MulTo函数 和 *=符号重载，在计算时把上一次运算的值参与到下一次运算了。。
![image](https://user-images.githubusercontent.com/23358242/62033324-494c2200-b21e-11e9-870c-976084726eba.png)
这是运算时候发现的问题
![image](https://user-images.githubusercontent.com/23358242/62033405-70a2ef00-b21e-11e9-9b58-3602006b7415.png)
--来自你的小迷弟

**Comment by Ubpa** [comment]
这个bug我之前修复过了该接口已经删除了更新一下就好------------------ 原始邮件 ------------------发件人: yjh  <notifications@github.com>发送时间: 2019年7月29日 16:32收件人: Ubpa/RenderLab <RenderLab@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[Ubpa/RenderLab] U老师您数学库矩阵运算有点Bug (#3)在Mat4x4.h的 MulTo函数 和 *=符号重载，在计算时把上一次运算的值参与到下一次运算了。。

这是运算时候发现的问题

--来自你的小迷弟

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ubpa/RenderLab/issues/3?email_source=notifications\u0026email_token=ADTHQT3IRX5JA5FILZKVGTTQB2TK7A5CNFSM4IHQAJ62YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HB7OOXA",
"url": "https://github.com/Ubpa/RenderLab/issues/3?email_source=notifications\u0026email_token=ADTHQT3IRX5JA5FILZKVGTTQB2TK7A5CNFSM4IHQAJ62YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HB7OOXA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ubpa** [comment]
实在抱歉造成了困扰 >_<

**Comment by fakersaber** [comment]
哇亲自回我啦φ(゜▽゜*)♪，没有困扰啦~您是我前进的方向
